spring.application.name=Query-Application

# PostgreSQL properties
#spring.datasource.url=jdbc:postgresql://localhost:5432/querydesk
#spring.datasource.username=postgres
#spring.datasource.password=experion@123


# Connection via Supavisor (Connection Pooling)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
spring.datasource.username=postgres.kwgadkcdblkfbxnoxuvs
spring.datasource.password=querydesk@123



# SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=create

# Enable logging
management.endpoints.web.exposure.include=*
management.endpoint.loggers.enabled=true

# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=querydesk0@gmail.com
spring.mail.password=lyve xsap gpvy tpyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
logging.level.org.springframework.mail=DEBUG

